site_name: dRAX - 2022.3.1 release

site_url: https://accelleran.github.io/drax-docs-2022-3-1/
theme: 
  logo: images/accelleran_logo.png
  favicon: images/accelleran_favicon.png
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
extra:
  version:
    provider: mike
plugins:
  - search:
  - mike:
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
#  - enumerate-headings 
  - section-index
extra_css:
  - css/extra.css
nav:
    - 'index.md'
    - 'kubernetes-install/index.md'
    - 'drax-install/index.md'
    - 'du-install/index.md'
    - 'core-install/index.md'
