site_name: Accelleran 5G O-RAN System Installation Guide

site_url: 'https://accelleran.github.io/drax-docs/'
theme: 
  logo: images/accelleran_logo.png
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

extra:
  version:
    provider: mike
plugins:
  - search:
  - mike:
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
  # - enumerate-headings 
  - section-index
extra_css:
  - css/extra.css
nav:
  - '[2023.3.0] System Release':
    - '2023.3.0_files/index.md'
    - '2023.3.0_files/machine-prep/index.md'
    - '2023.3.0_files/kubernetes_ng-install/index.md'
    - '2023.3.0_files/drax_ng-install/index.md'
    - '2023.3.0_files/cu_ng-install/index.md'
    - '2023.3.0_files/cw_ng-install/index.md'
    - '2023.3.0_files/core-install/index.md'
    - '2023.3.0_files/effnet-benetel-prep/index.md'
    - '2023.3.0_files/extra-info/index.md'
  - '[next 2024.1.0] System Release':
    - '2024.1.0_files/index.md'
    - '2024.1.0_files/machine-prep/index.md'
    - '2024.1.0_files/kubernetes_ng-install/index.md'
    - '2024.1.0_files/drax_ng-install/index.md'
    - '2024.1.0_files/cu_ng-install/index.md'
    - '2024.1.0_files/cw_ng-install/index.md'
    - '2024.1.0_files/core-install/index.md'
    - '2024.1.0_files/effnet-benetel-prep/index.md'
    - '2024.1.0_files/srsran-benetel-prep/index.md'
    - '2024.1.0_files/extra-info/index.md'
